"""Gauge model 'units' changed to 'unit'

Revision ID: 48dc48170a69
Revises: d610d8610451
Create Date: 2023-08-15 15:05:15.194087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dc48170a69'
down_revision = 'd610d8610451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gauge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=64), nullable=True))
        batch_op.drop_column('units')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gauge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
