"""reset

Revision ID: 67025b4d4b58
Revises: 48dc48170a69
Create Date: 2023-08-16 12:45:19.130320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67025b4d4b58'
down_revision = '48dc48170a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gauge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.alter_column('ei',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('min_value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_value',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sunlight_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moisture_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reaction_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nutrient_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salinity_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('salinity_status')
        batch_op.drop_column('nutrient_status')
        batch_op.drop_column('reaction_status')
        batch_op.drop_column('moisture_status')
        batch_op.drop_column('sunlight_status')
        batch_op.drop_column('created')

    with op.batch_alter_table('gauge', schema=None) as batch_op:
        batch_op.alter_column('max_value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('min_value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ei',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
