"""Sensor model column type changed

Revision ID: 9b72ec61831b
Revises: 11e80d6e649b
Create Date: 2023-06-28 12:10:00.317270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b72ec61831b'
down_revision = '11e80d6e649b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_measurements', schema=None) as batch_op:
        batch_op.alter_column('moisture',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_measurements', schema=None) as batch_op:
        batch_op.alter_column('moisture',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
