"""pot table upgrade

Revision ID: aa24973d1650
Revises: b2255acb297f
Create Date: 2023-08-12 16:25:23.343514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa24973d1650'
down_revision = 'b2255acb297f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('light_gauge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ei', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('units', sa.String(length=64), nullable=True))

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sunlight_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moisture_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reaction_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nutrient_status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salinity_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('salinity_status')
        batch_op.drop_column('nutrient_status')
        batch_op.drop_column('reaction_status')
        batch_op.drop_column('moisture_status')
        batch_op.drop_column('sunlight_status')
        batch_op.drop_column('created')

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('light_gauge', schema=None) as batch_op:
        batch_op.drop_column('units')
        batch_op.drop_column('ei')

    # ### end Alembic commands ###
