"""plant image nullable=False

Revision ID: b2255acb297f
Revises: 0cac098b2aa2
Create Date: 2023-07-17 14:20:52.280641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2255acb297f'
down_revision = '0cac098b2aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_plant')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.create_table('_alembic_tmp_plant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('salinity', sa.VARCHAR(length=64), nullable=True),
    sa.Column('temperature', sa.INTEGER(), nullable=True),
    sa.Column('ph_range', sa.VARCHAR(length=64), nullable=True),
    sa.Column('moisture', sa.VARCHAR(length=64), nullable=True),
    sa.Column('shade', sa.VARCHAR(length=64), nullable=True),
    sa.Column('soil_texture', sa.VARCHAR(length=64), nullable=True),
    sa.Column('substrate', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('photo', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
