"""update

Revision ID: c3ddb5139eeb
Revises: d32d26858a87
Create Date: 2023-08-28 19:05:30.091041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ddb5139eeb'
down_revision = 'd32d26858a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunlight', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reaction', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('nutrient', sa.String(length=64), nullable=True))
        batch_op.alter_column('temperature',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_column('shade')
        batch_op.drop_column('ph_range')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph_range', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('shade', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('temperature',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('nutrient')
        batch_op.drop_column('reaction')
        batch_op.drop_column('sunlight')

    # ### end Alembic commands ###
