"""model Pot update

Revision ID: c510048ff752
Revises: ced8be3490d4
Create Date: 2023-08-20 15:08:37.599510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c510048ff752'
down_revision = 'ced8be3490d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('temperature_status')

    # ### end Alembic commands ###
