"""model update

Revision ID: d610d8610451
Revises: aa24973d1650
Create Date: 2023-08-15 14:33:56.440965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd610d8610451'
down_revision = 'aa24973d1650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('light_gauge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('light_gauge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eiv', sa.INTEGER(), nullable=False),
    sa.Column('min_value', sa.INTEGER(), nullable=True),
    sa.Column('max_value', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=128), nullable=True),
    sa.Column('ei', sa.VARCHAR(length=64), nullable=True),
    sa.Column('units', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
